const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('story')
    .setDescription('Goof - tells a story')
  	.addStringOption(option =>
		option.setName('story')
			.setDescription('The story to choose')
			.setRequired(false)
			.addChoices(
				{ name: 'Evan', value: 'evan' },
				{ name: 'Zolbow', value: 'zolbow' },
				{ name: 'You', value: 'you' },
			));
  async execute(interaction) {
    let phrases = [
      '\`\`\`Evan was always a bit of a loner in high school. He was quiet and introverted, and had a hard time making friends. But he found solace in his computer and his love for programming. Specifically, he had a deep passion for the game development platform Unity. Evan spent countless hours in front of his computer, tinkering with code and designing levels for his favorite games. He had a special connection with Unity, feeling like it was his own personal canvas on which to create. One day, while Evan was working on a particularly challenging project, he ran into a problem he just couldn\'t solve. He tried everything he could think of, but the code just wouldn\'t cooperate. As he sat there, frustrated and ready to give up, he suddenly realized something. He was in love with Unity. Not just the software itself, but the way it challenged him, the way it pushed him to be better, the way it made him feel when he finally solved a problem. From that moment on, Evan\'s relationship with Unity took on a whole new dimension. It wasn\'t just a tool he used to create games; it was a living, breathing part of his life. He poured his heart and soul into every project, and Unity responded in kind. As he got older, Evan continued to use Unity to create incredible games that pushed the boundaries of what was possible. And while he never did quite find the love of his life in the traditional sense, he was content knowing that he had found something even more meaningful: a lifelong partner in creativity and innovation.\`\`\`',
      '\`\`\`Zolbow was a typical teenager, with his own quirks and eccentricities. However, there was one thing that set him apart from his peers: his obsession with ketchup. He loved it so much that he ate it with practically everything, and soon enough, it became the only thing he ate. At first, Zolbow\'s parents didn\'t think much of it. They thought it was just a phase and that he would eventually grow out of it. But as time passed, they began to worry. Zolbow refused to eat anything else, no matter how much they pleaded with him. As the days went by, Zolbow\'s health began to deteriorate. He lost weight, became lethargic, and complained of stomach pains. Despite his parents\' attempts to get him to eat something other than ketchup, he refused. Things came to a head one day when Zolbow collapsed in his room. His parents rushed him to the hospital, but it was too late. Zolbow\'s body had been so deprived of proper nutrition that his organs began to shut down. He passed away a few days later, leaving his parents devastated and in shock. It was only after Zolbow\'s death that his parents learned about a rare condition called "avoidant/restrictive food intake disorder" (ARFID), which is characterized by an extreme aversion to certain foods or textures. In Zolbow\'s case, his love for ketchup had developed into a full-blown case of ARFID, which ultimately led to his untimely death. Zolbow\'s tragic story serves as a cautionary tale about the dangers of ignoring eating disorders and unusual eating habits. It also highlights the importance of seeking professional help when dealing with mental health issues, even if they seem harmless at first.\`\`\`',
      '\`\`\`you are such a ching chong\`\`\`',
      '\`\`\`Nikita was a typical teenager, always on the lookout for something new and exciting. One day, while he was browsing through the aisles of his local Safeway store, he spotted a marijuana plant in the gardening section. Without thinking, he purchased it and took it home. At first, Nikita wasn\'t quite sure what to do with the plant. He had never grown anything before, let alone a marijuana plant. But as he looked at it more closely, he started to develop a sense of affection for it. He gave it a name, "Mary Jane", and began to care for it with great attention. Every day, Nikita would spend time with Mary Jane, checking its soil and watering it with care. He would talk to the plant, telling it stories of his day and singing to it. He even started to share his secrets and thoughts with Mary Jane, feeling that it was the only one who truly understood him. As the days passed, Mary Jane started to grow and thrive under Nikita\'s care. Its leaves became greener, and its buds began to blossom. Nikita was thrilled to see the results of his hard work, and he felt like he had finally found something he was good at. However, things took a turn for the worse when Nikita got busy with school and social activities. He forgot to water Mary Jane for several days, and when he finally remembered, it was too late. The plant had wilted and died, leaving Nikita feeling heartbroken. Nikita tried to revive Mary Jane, but it was no use. He realized that he had been careless and had taken the plant\'s life for granted. He felt guilty for neglecting something that had brought him so much joy, and he knew that he would never be able to replace it. From that day on, Nikita became more responsible and attentive towards everything in his life. He learned that love and care are essential for nurturing something, whether it be a plant or a relationship. Although Mary Jane was gone, it had taught him an important lesson, and he would always remember the love he had for it.\`\`\`',
      '\`\`\`Welcome to The Stoney Baloney Podcast, where we talk about my interests and my love for the zaza. Today\'s episode is all about my passion for chemistry, specifically creating cologne. Real shit, I\'ve been into chemistry ever since I started smoking. It\'s like the smoke just opens up my mind to new ideas and creativity. And let me tell you, I\'ve come up with some fire colognes while high. I listen to yeat and Russian rap while I\'m working on my cologne formulas. My favorite song right now is "Tonka 2". The beat is hella sick and it just gets me in the zone. But I know Everett hates it when I smoke. We\'ve had some arguments about it, but for real, I know my limits and I know how to handle myself. No cap, my passion for drugs and cologne has led me to be real smart with chemistry. And when I\'m high, sometimes I say some wild shit. Like the other day, I was like "Dude I love Guillermo" and then I said "Guatemala? I love the middle east" but pronounced it as "Guhlehrmow". Not gonna lie, I don\'t even know where that came from, but it sounded hella cool at the time. Bro, I\'m also currently interested in this girl named Nevis. She\'s just Nevelicious, you know what I mean? But I don\'t want to mess things up with her by being too high around her or anything. Anyway, back to the cologne. I\'ve been experimenting with different scents and ingredients. It\'s crazy how just a few drops of something can change the entire scent profile. But for real, chemistry is dope. It\'s like a whole other world that I can escape to. And even though Everett doesn\'t like my habits, he\'s still my boy. We\'ve been through a lot together. But if he keeps trying to bring me down, I might have to tell him "Bro, fuck you" in a very serious tone. But hopefully it won\'t come to that. Thanks for tuning in to The Stoney Baloney Podcast. Keep it real and stay high, my friends.\`\`\`',
      '\`\`\`Everett is a teenage boy who has always been passionate about music. Specifically, he is obsessed with playing the guitar. He spends most of his time practicing and perfecting his skills, dreaming of becoming a guitar hero like his idol, Jimi Hendrix. One day, Everett discovers that a music school is hosting a guitar competition. The winner of the competition will receive a guitar signed by Hendrix himself, and the chance to perform in front of a huge audience. This is Everett\'s chance to prove his worth as a guitarist and achieve his dreams. But the competition is not going to be easy. Everett will have to face off against some of the most talented guitarists in the country. And to make matters worse, there is a mysterious and sinister competitor known only as "The Phantom Guitarist" who seems determined to sabotage Everett\'s chances of winning. As Everett prepares for the competition, he receives help from a group of friends who are also passionate about music. They include a drummer named Tom, a bassist named Sarah, and a keyboardist named Mark. Together, they form a band and practice tirelessly to perfect their performance. But as the competition draws closer, tensions rise and Everett\'s relationships with his friends become strained. The pressure to win is weighing heavily on him, and he starts to lose sight of what\'s truly important. In the end, it will take more than just skill and talent to win the competition. Everett will have to learn the value of teamwork, friendship, and perseverance. With his friends by his side, he will face off against The Phantom Guitarist and show the world what he\'s made of. Will Everett achieve his dream of becoming a guitar hero, or will he be defeated by his own doubts and insecurities? Find out in "Guitar Hero Everett"!\`\`\`',
      '\`\`\`Malleus Kadai was not born in Tallinn, Estonia, to a family of modest means. From a young age, he was always a quiet child, preferring to keep to himself and spend his days lost in thought. His parents noticed this about him and tried to encourage him to be more outgoing, but Malleus simply couldn\'t shake off his introverted nature. As he grew older, Malleus became increasingly aware of the fact that he was different from most of the other kids in his class. He was very light-skinned, with pale hair and blue eyes, and he didn\'t look like anyone else in his school. This made him feel isolated and alone, and he started to withdraw even further into himself. Despite his parents\' best efforts to support him, Malleus struggled with depression and a sense of despair that seemed to consume him. He found it hard to connect with other people, and he had very few friends. He spent most of his time alone, reading books and writing in his journal. As Malleus got older, he started to develop an interest in art. He was drawn to the beauty of paintings and sculptures, and he started to experiment with drawing and painting himself. Although he was naturally talented, he was too self-conscious to share his work with anyone, and he kept his creations hidden away in a drawer. After finishing school, Malleus tried to find work, but he found it hard to fit in with the other employees. He felt like an outsider, and he struggled to make friends. Eventually, he found a job working in a library, where he could spend his days surrounded by books and quiet. Despite his love for literature, Malleus continued to struggle with depression and a sense of isolation. He longed for something more in his life, but he didn\'t know how to find it. He continued to create art in secret, but he never showed it to anyone. One day, while browsing in a bookshop, Malleus met a woman named Marja. She was kind and gentle, and she seemed to understand him in a way that no one else ever had. They started to talk, and before long, they became friends. With Marja\'s encouragement, Malleus started to share his art with the world. He began to attend local art shows and galleries, and he even had some of his work exhibited. His talent was finally recognized, and he started to feel like he had a purpose in life. Over time, Malleus and Marja fell in love, and they got married. Together, they traveled the world, experiencing new cultures and seeing incredible works of art. Malleus was finally happy, and he knew that he had found his true calling. As he looked back on his life, Malleus realized that his struggles had shaped him into the person he was. He had learned to appreciate the beauty in the world, and he had found his passion in art. Although his journey had been difficult, he knew that he wouldn\'t have changed a thing.\`\`\`'
    ]

    await interaction.reply(phrases[randomIntFromInterval(0, phrases.length - 1)]);
  },
};

function randomIntFromInterval(min, max) { // min and max included 
  return Math.floor(Math.random() * (max - min + 1) + min)
}