const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('story')
    .setDescription('Goof - tells a story'),
  async execute(interaction) {
    let phrases = [
      '\`\`\`Evan was always a bit of a loner in high school. He was quiet and introverted, and had a hard time making friends. But he found solace in his computer and his love for programming. Specifically, he had a deep passion for the game development platform Unity. Evan spent countless hours in front of his computer, tinkering with code and designing levels for his favorite games. He had a special connection with Unity, feeling like it was his own personal canvas on which to create. One day, while Evan was working on a particularly challenging project, he ran into a problem he just couldn\'t solve. He tried everything he could think of, but the code just wouldn\'t cooperate. As he sat there, frustrated and ready to give up, he suddenly realized something. He was in love with Unity. Not just the software itself, but the way it challenged him, the way it pushed him to be better, the way it made him feel when he finally solved a problem. From that moment on, Evan\'s relationship with Unity took on a whole new dimension. It wasn\'t just a tool he used to create games; it was a living, breathing part of his life. He poured his heart and soul into every project, and Unity responded in kind. As he got older, Evan continued to use Unity to create incredible games that pushed the boundaries of what was possible. And while he never did quite find the love of his life in the traditional sense, he was content knowing that he had found something even more meaningful: a lifelong partner in creativity and innovation.\`\`\`',
      '\`\`\`Zolbow was a typical teenager, with his own quirks and eccentricities. However, there was one thing that set him apart from his peers: his obsession with ketchup. He loved it so much that he ate it with practically everything, and soon enough, it became the only thing he ate. At first, Zolbow\'s parents didn\'t think much of it. They thought it was just a phase and that he would eventually grow out of it. But as time passed, they began to worry. Zolbow refused to eat anything else, no matter how much they pleaded with him. As the days went by, Zolbow\'s health began to deteriorate. He lost weight, became lethargic, and complained of stomach pains. Despite his parents\' attempts to get him to eat something other than ketchup, he refused. Things came to a head one day when Zolbow collapsed in his room. His parents rushed him to the hospital, but it was too late. Zolbow\'s body had been so deprived of proper nutrition that his organs began to shut down. He passed away a few days later, leaving his parents devastated and in shock. It was only after Zolbow\'s death that his parents learned about a rare condition called "avoidant/restrictive food intake disorder" (ARFID), which is characterized by an extreme aversion to certain foods or textures. In Zolbow\'s case, his love for ketchup had developed into a full-blown case of ARFID, which ultimately led to his untimely death. Zolbow\'s tragic story serves as a cautionary tale about the dangers of ignoring eating disorders and unusual eating habits. It also highlights the importance of seeking professional help when dealing with mental health issues, even if they seem harmless at first.\`\`\`',
      'you are such a ching chong',
      '\`\`\`Nikita was a typical teenager, always on the lookout for something new and exciting. One day, while he was browsing through the aisles of his local Safeway store, he spotted a marijuana plant in the gardening section. Without thinking, he purchased it and took it home. At first, Nikita wasn\'t quite sure what to do with the plant. He had never grown anything before, let alone a marijuana plant. But as he looked at it more closely, he started to develop a sense of affection for it. He gave it a name, "Mary Jane", and began to care for it with great attention. Every day, Nikita would spend time with Mary Jane, checking its soil and watering it with care. He would talk to the plant, telling it stories of his day and singing to it. He even started to share his secrets and thoughts with Mary Jane, feeling that it was the only one who truly understood him. As the days passed, Mary Jane started to grow and thrive under Nikita\'s care. Its leaves became greener, and its buds began to blossom. Nikita was thrilled to see the results of his hard work, and he felt like he had finally found something he was good at. However, things took a turn for the worse when Nikita got busy with school and social activities. He forgot to water Mary Jane for several days, and when he finally remembered, it was too late. The plant had wilted and died, leaving Nikita feeling heartbroken. Nikita tried to revive Mary Jane, but it was no use. He realized that he had been careless and had taken the plant\'s life for granted. He felt guilty for neglecting something that had brought him so much joy, and he knew that he would never be able to replace it. From that day on, Nikita became more responsible and attentive towards everything in his life. He learned that love and care are essential for nurturing something, whether it be a plant or a relationship. Although Mary Jane was gone, it had taught him an important lesson, and he would always remember the love he had for it.\`\`\`'
    ]

    await interaction.reply(phrases[randomIntFromInterval(0, phrases.length)]);
  },
};

function randomIntFromInterval(min, max) { // min and max included 
  return Math.floor(Math.random() * (max - min + 1) + min)
}